MEmu = Final Burn Alpha
MEmuV = v0.2.97.23
MURL = http://www.barryharris.me.uk/
MAuthor = djvj
MVersion = 2.0.1
MCRC = A317CAA5
iCRC =
MID = 635038268890292583
MSystem = "Final Burn Alpha","NEC TurboGrafx-16","NEC PC Engine","NEC SuperGrafx","Sega Mega Drive","SNK Neo Geo"
;----------------------------------------------------------------------------
; Notes:
; You must have your roms renamed using clrmame and the dat generated by FBA. Run FBA manually and goto Misc->Generate dat file->Generate dat...
; Open FBA manually and select MISC->Configure ROM paths... and define at least one path to your roms.
; Fullscreen is now automatic when running FBA via command line
; FBA supports 7z, so no need for hyperlaunch 7z functions
;----------------------------------------------------------------------------
StartModule()
FadeInStart()

If systemname in NEC TurboGrafx-16,NEC PC Engine,NEC SuperGrafx,Sega Mega Drive
{	; The object controls how the module reacts to different systems. FBA can play a lot of systems, but the romName changes slightly so this module has to adapt 
	mType := Object("NEC TurboGrafx-16","tg_","NEC PC Engine","pce_","NEC SuperGrafx","sgx_","Sega Mega Drive","md_")
	ident := mType[systemName]	; search 1st array for the systemName identifier mednafen uses
	If !ident
		ScriptError("Your systemName is: " . systemName . "`nIt is not one of the known supported systems for this FBA module: " . moduleName)
}

fbaRomName := (If ident ? ident : "") . romName	; FBA requires an identifier prefix attached to the romName which tells FBA what system to run

Run(executable . " """ . fbaRomName . """", emuPath)

WinWait("ahk_class FB Alpha")
WinWaitActive("ahk_class FB Alpha")

; This loops detects the rom loading window and breaks when it's done. Only here to avoid using too many WinWait commands from all the odd flashing the emu does.
Loop {
	IfWinActive, ahk_class #32770
		Break
	Sleep, 50
}

; This loop detects when the emu window is done flashing back and forth between HS and the emu window and is actually in the game.
Loop {
	If x = 10
		Break
	IfWinActive, ahk_class FB Alpha
		x++
	WinActivate, ahk_class FB Alpha
	Sleep, 50
}

FadeInExit()

WinActivate, ahk_class FB Alpha

Process("WaitClose", executable)
FadeOutExit()
ExitModule()


CloseProcess:
	FadeOutStart()
	WinClose("ahk_class FB Alpha")
Return
